services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/fapai_db
      - JWT_SECRET=${JWT_SECRET}
      - WECHAT_APPID=wx1b250ad4e69950e8
      - WECHAT_SECRET=1b2b39ba50e045a1b90bd6a460c7ca20
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
